ALTER TABLE "ANALYSIS" ADD COLUMN IF NOT EXISTS "SOURCE" VARCHAR(50);

CREATE INDEX IF NOT EXISTS "ANALYSIS_SOURCE_IDX" ON "ANALYSIS" ("SOURCE");

-- Backfill: analyses linked to vulnerability policies get POLICY source
UPDATE "ANALYSIS"
SET "SOURCE" = 'POLICY'
WHERE "VULNERABILITY_POLICY_ID" IS NOT NULL
  AND "SOURCE" IS NULL;

-- Backfill: other analyses with meaningful data get MANUAL source
UPDATE "ANALYSIS"
SET "SOURCE" = 'MANUAL'
WHERE "SOURCE" IS NULL
  AND (
      ("STATE" IS NOT NULL AND "STATE" != 'NOT_SET')
      OR ("JUSTIFICATION" IS NOT NULL AND "JUSTIFICATION" != 'NOT_SET')
      OR ("RESPONSE" IS NOT NULL AND "RESPONSE" != 'NOT_SET')
      OR "SEVERITY" IS NOT NULL
      OR "CVSSV2VECTOR" IS NOT NULL
      OR "CVSSV3VECTOR" IS NOT NULL
      OR "CVSSV4VECTOR" IS NOT NULL
      OR "OWASPVECTOR" IS NOT NULL
  );
