### Change Admin Password

POST /api/v1/user/forceChangePassword
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin&newPassword={{ adminPassword }}&confirmPassword={{ adminPassword }}

### Login as Admin

POST /api/v1/user/login
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded

username=admin&password={{ adminPassword}}

> {% client.global.set("bearerToken", response.body.trim()); %}

### Delete Project

DELETE /api/v1/project/{{ projectUUID }}
Host: localhost:8080
Authorization: Bearer {{bearerToken}}

### Create Project

PUT /api/v1/project
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "{{ projectName }}",
  "version": "{{ projectVersion }}",
  "classifier": "APPLICATION"
}

> {% client.global.set("projectUUID", response.body["uuid"]); %}

### Get Project

GET /api/v1/project/lookup?name={{ projectName }}&version={{ projectVersion }}
Host: localhost:8080
Authorization: Bearer {{ bearerToken }}

> {% client.global.set("projectUUID", response.body["uuid"]); %}

### Upload BOM

POST /api/v1/bom
Host: localhost:8080
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{ bearerToken }}

--boundary
Content-Disposition: form-data; name="bom"; filename="bom.xml"

< src/test/resources/bom-1.xml

--boundary
Content-Disposition: form-data; name="projectName"

{{ projectName }}

--boundary
Content-Disposition: form-data; name="projectVersion"

{{ projectVersion }}

--boundary--

> {% client.global.set("bomUploadToken", response.body["token"]); %}

### Check BOM Upload Token Status

GET /api/v1/bom/token/{{ bomUploadToken }}
Host: localhost:8080
Authorization: Bearer {{ bearerToken }}

### Get Project Findings

GET /api/v1/finding/project/{{ projectUUID }}
Host: localhost:8080
Authorization: Bearer {{ bearerToken }}
