# This file is part of Dependency-Track.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) OWASP Foundation. All Rights Reserved.
openapi: 3.0.0
info:
  title: OWASP Dependency-Track
  description: REST API of OWASP Dependency-Track
  version: 2.0.0
  contact:
    name: The Dependency-Track Authors
    email: dependencytrack@owasp.org
    url: https://github.com/DependencyTrack/dependency-track
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
security:
  - apiKeyAuth: [ ]
  - bearerAuth: [ ]
servers:
  - url: /api/v2
tags:
  - name: foo
    description: bar
  - name: workflow
    description: /workflow
paths:
  /token/{uuid}/status:
    get:
      tags:
        - workflow
      summary: Retrieves workflow states associated with the token received from bom upload.
      description: Requires permission <strong>BOM_UPLOAD</strong>
      operationId: getWorkflowStates
      parameters:
        - name: uuid
          in: path
          description: The UUID of the token to query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A list of workflow states
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowState'
        '401':
          description: Unauthorized
        '404':
          description: Workflow does not exist
      security:
        - apiKeyAuth: [ ]
        - bearerAuth: [ ]
components:
  schemas:
    WorkflowState:
      type: object
      properties:
        id:
          type: integer
        parent:
          $ref: '#/components/schemas/WorkflowState'
        step:
          type: string
          enum:
            - BOM_CONSUMPTION
            - BOM_PROCESSING
            - VULN_ANALYSIS
            - REPO_META_ANALYSIS
            - POLICY_EVALUATION
            - METRICS_UPDATE
            - POLICY_BUNDLE_SYNC
            - PROJECT_CLONE
        status:
          type: string
          enum:
            - PENDING
            - TIMED_OUT
            - COMPLETED
            - FAILED
            - CANCELLED
            - NOT_APPLICABLE
        failureReason:
          type: string
        token:
          type: string
          format: uuid
        startedAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
  securitySchemes:
    apiKeyAuth:
      name: X-Api-Key
      description: Authentication via API key
      type: apiKey
      in: header
    bearerAuth:
      description: Authentication via Bearer token
      type: http
      scheme: Bearer