CREATE TABLE public."APIKEY" (
    "ID" bigint NOT NULL,
    "APIKEY" character varying(255), -- When the change runs, this column still exists.
    "COMMENT" character varying(255),
    "CREATED" timestamp with time zone,
    "LAST_USED" timestamp with time zone,
    "SECRET_HASH" character varying(64), -- When the change runs, this column is still nullable.
    "PUBLIC_ID" character varying(8), -- When the change runs, this column is still nullable.
    "IS_LEGACY" boolean DEFAULT false NOT NULL
);

ALTER TABLE public."APIKEY" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."APIKEY_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public."APIKEY"
    ADD CONSTRAINT "APIKEY_PK" PRIMARY KEY ("ID");

-- When the change runs, this index still exists.
CREATE UNIQUE INDEX "APIKEY_IDX" ON public."APIKEY" USING btree ("APIKEY");