CREATE TABLE IF NOT EXISTS "SHEDLOCK" (
	"NAME" VARCHAR(64) NOT NULL,
  	"LOCK_UNTIL" TIMESTAMP NOT NULL,
    "LOCKED_AT" TIMESTAMP NOT NULL,
	"LOCKED_BY" VARCHAR(255) NOT NULL,
	CONSTRAINT "SHEDLOCK_PK" PRIMARY KEY ("NAME"));