CREATE OR REPLACE FUNCTION "COMPONENT_INTEGRITY_CHECK_STATUS"(
  "md5_status" TEXT
, "sha1_status" TEXT
, "sha256_status" TEXT
, "sha512_status" TEXT
) RETURNS TEXT
  LANGUAGE "sql"
  PARALLEL SAFE
  IMMUTABLE
AS
$$
 SELECT CASE
   WHEN 'COMPONENT_MISSING_HASH_AND_MATCH_UNKNOWN' = ALL(ARRAY["md5_status", "sha1_status", "sha256_status", "sha512_status"]) THEN 'COMPONENT_MISSING_HASH_AND_MATCH_UNKNOWN'
   WHEN ARRAY['COMPONENT_MISSING_HASH_AND_MATCH_UNKNOWN', 'COMPONENT_MISSING_HASH'] <@ ARRAY["md5_status", "sha1_status", "sha256_status", "sha512_status"] THEN 'COMPONENT_MISSING_HASH'
   WHEN ARRAY['COMPONENT_MISSING_HASH_AND_MATCH_UNKNOWN', 'HASH_MATCH_UNKNOWN'] <@ ARRAY["md5_status", "sha1_status", "sha256_status", "sha512_status"] THEN 'HASH_MATCH_UNKNOWN'
   WHEN 'HASH_MATCH_FAILED' = ANY(ARRAY["md5_status", "sha1_status", "sha256_status", "sha512_status"]) THEN 'HASH_MATCH_FAILED'
   ELSE 'HASH_MATCH_PASSED'
 END
$$;