CREATE OR REPLACE FUNCTION "MATCH_COMPONENT_HASH"(
  "actual" TEXT
, "expected" TEXT
) RETURNS TEXT
  LANGUAGE "sql"
  PARALLEL SAFE
  IMMUTABLE
AS
$$
 SELECT CASE
   WHEN "actual" IS NULL AND "expected" IS NULL THEN 'COMPONENT_MISSING_HASH_AND_MATCH_UNKNOWN'
   WHEN "actual" IS NULL THEN 'COMPONENT_MISSING_HASH'
   WHEN "expected" IS NULL THEN 'HASH_MATCH_UNKNOWN'
   WHEN "actual" = "expected" THEN 'HASH_MATCH_PASSED'
   ELSE 'HASH_MATCH_FAILED'
 END
$$;