CREATE OR REPLACE FUNCTION has_project_access(
  project_id BIGINT
, team_ids BIGINT[]
) RETURNS BOOL
  LANGUAGE "sql"
  PARALLEL SAFE
  STABLE
AS
$$
SELECT EXISTS(
  SELECT 1
    FROM "PROJECT_ACCESS_TEAMS"
   INNER JOIN "PROJECT_HIERARCHY"
      ON "PROJECT_HIERARCHY"."PARENT_PROJECT_ID" = "PROJECT_ACCESS_TEAMS"."PROJECT_ID"
   WHERE "PROJECT_ACCESS_TEAMS"."TEAM_ID" = ANY(team_ids)
     AND "PROJECT_HIERARCHY"."CHILD_PROJECT_ID" = project_id
)
$$;