name: Build CI

on:
  push:
    branches:
      - 'main'
      - '[0-9]+.[0-9]+.x' # Release branches
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

permissions: { }

jobs:
  call-build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      app-version: "snapshot"
      publish-container: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      packages: write # Required to push images to ghcr.io
      security-events: write # Required to upload trivy's SARIF output
    secrets:
      registry-0-usr: ${{ github.repository_owner }}
      registry-0-psw: ${{ secrets.GITHUB_TOKEN }}
