package org.dependencytrack.tasks;

public enum LockName {
    PORTFOLIO_METRICS_TASK_LOCK,
    LDAP_SYNC_TASK_LOCK,
    EPSS_MIRROR_TASK_LOCK,
    VULNERABILITY_METRICS_TASK_LOCK,
    INTERNAL_COMPONENT_IDENTIFICATION_TASK_LOCK,
    WORKFLOW_STEP_REAPER_TASK_LOCK
}
